# Theme Configuration System for Midnight Style

# Basic colors
background_color: "#0a192f"  # Dark navy background
container_background: "transparent"
text_color: "#ffffff"
description_color: "#8892b0"
section_heading_color: "#ffffff"

# Link styling
link_style:
  background_color: "#172a45"  # Darker card background
  text_color: "#64ffda"  # Teal text for titles
  description_color: "#8892b0"  # Lighter gray for descriptions
  border_radius: "8px"
  border: "2px solid"  # Will be overridden by card_colors
  shadow: true
  hover:
    transform: true
    background_color: "#1f3a60"
    shadow_increase: true

# Card styling
card_style:
  padding: "16px 20px"
  margin_bottom: "16px"
  display_icon: true
  icon_position: "left"
  icon_color: "#64ffda"  # Teal icons
  icon_background: "#172a45"
  icon_size: "24px"
  title_size: "18px"
  description_size: "14px"
  external_link_icon: true

# Section styling
section_style:
  display: true
  font_size: "24px"
  margin_top: "40px"
  margin_bottom: "20px"
  text_align: "center"

# Card colors (for borders)
card_colors:
  - "#50fa7b"  # Green
  - "#2d7de4"  # Blue
  - "#ff79c6"  # Pink
  - "#ffb86c"  # Orange
  - "#8be9fd"  # Cyan
  - "#bd93f9"  # Purple

# Avatar styling
avatar_style:
  size: "120px"
  border: "4px solid #64ffda"
  shadow: true

# Container styling
container_style:
  max_width: "700px"
  padding: "40px 20px"
  border_radius: "0px"
  shadow: false

# Animation
animations:
  link_hover: true
  page_load: true
